source .env
export PGPASSWORD=$DATABASE_PASSWORD
psql -h $DATABASE_IP -U $DATABASE_USER -p $DATABASE_PORT -c "DROP DATABASE museum;"
psql -h $DATABASE_IP -U $DATABASE_USER -p $DATABASE_PORT -c "CREATE DATABASE museum;"
psql -h $DATABASE_IP -U $DATABASE_USER $DATABASE_NAME -p $DATABASE_PORT -f schema.sql
